### ISSUE TITLE
Mac M1 and VS devcontainer - Unsupported platform/architecture combination linux/arm

### ISSUE THREAD

**Issue by hagsonz** [Shopify/function-runner#167]
What version? (`function-runner --version`): ...
3.6.0

## Problem
can't run `npm exec -- shopify app function run` on  Mac M1 chip and vscode dev container.
It was working before...
```
## Error Message and Context
function-runner v3.6.0 is not available locally.
function-runner needs to be downloaded...
file:///workspaces/ahava-extensions-1/node_modules/@shopify/function-runner/index.js:147
    throw Error(
          ^

Error: Unsupported platform/architecture combination linux/arm
    at platarch (file:///workspaces/ahava-extensions-1/node_modules/@shopify/function-runner/index.js:147:11)
    at binaryUrl (file:///workspaces/ahava-extensions-1/node_modules/@shopify/function-runner/index.js:106:77)
    at compressedStream (file:///workspaces/ahava-extensions-1/node_modules/@shopify/function-runner/index.js:59:17)
    at new Promise (<anonymous>)
    at downloadBinary (file:///workspaces/ahava-extensions-1/node_modules/@shopify/function-runner/index.js:58:34)
    at main (file:///workspaces/ahava-extensions-1/node_modules/@shopify/function-runner/index.js:24:13)

Node.js v18.16.0
── external error ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Error coming from `npm exec -- function-runner -f /workspaces/ahava-extensions-1/extensions/order-bump-product-discount/dist/function.wasm`

Command failed with exit code 1: npm exec -- function-runner -f /workspaces/ahava-extensions-1/extensions/order-bump-product-discount/dist/function.wasm

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

## Steps to reproduce
execute `npm exec -- shopify app function run`

**Comment by andrewhassan** [comment]
No worries at all! Version 4.0.2 didn't have support for ARM on Linux. However, newer versions of the `@shopify/function-runner` package do! I'd recommend updating to the newest version, which is `4.1.1`.
