### ISSUE TITLE
Failed to download function-runner v4.0.0 for arm-macos

### ISSUE THREAD

**Issue by Sam115200** [Shopify/function-runner#182]
What version? (`function-runner --version`): 
```
> testapp@1.0.0 test /Users/sam/Desktop/shopify/testapp
> function-runner --version

function-runner v4.0.0 is not available locally.
function-runner needs to be downloaded...
Downloading function-runner v4.0.0 to /Users/sam/Library/Caches/binarycache/function-runner-v4.0.0...
file:///Users/sam/Desktop/shopify/testapp/node_modules/.pnpm/@shopify+function-runner@4.1.1/node_modules/@shopify/function-runner/index.js:63
      return reject(new Error(`Failed to download ${NAME} ${version} for ${platarch()}.`))
                    ^

Error: Failed to download function-runner v4.0.0 for arm-macos.
    at compressedStream (file:///Users/sam/Desktop/shopify/testapp/node_modules/.pnpm/@shopify+function-runner@4.1.1/node_modules/@shopify/function-runner/index.js:63:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.5.0
 ELIFECYCLE  Test failed. See above for more details.
```

## Problem
Unable to run function-runner at all. It tries to download v4.0.0 and fails.

## Error Message and Context
```
> testapp@1.0.0 function:run /Users/sam/Desktop/shopify/testapp
> function-runner -f extensions/$NAME/target/wasm32-wasi/release/$NAME.wasm extensions/$NAME/test_input.json

function-runner v4.0.0 is not available locally.
function-runner needs to be downloaded...
Downloading function-runner v4.0.0 to /Users/sam/Library/Caches/binarycache/function-runner-v4.0.0...
file:///Users/sam/Desktop/shopify/testapp/node_modules/.pnpm/@shopify+function-runner@4.1.1/node_modules/@shopify/function-runner/index.js:63
      return reject(new Error(`Failed to download ${NAME} ${version} for ${platarch()}.`))
                    ^

Error: Failed to download function-runner v4.0.0 for arm-macos.
    at compressedStream (file:///Users/sam/Desktop/shopify/testapp/node_modules/.pnpm/@shopify+function-runner@4.1.1/node_modules/@shopify/function-runner/index.js:63:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.5.0
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
```

## Steps to reproduce
1. I am using Apple macbook 2021, Apple M1 Pro, macOS 13.4.1. 
2. Simply try to run any function runner command and it fails to download function runner. Seems like this change only happened yesterday. Previously it used to work without any issues.

**Comment by Jay-Plumb** [comment]
Should be resolved now - see https://github.com/Shopify/cli/issues/2688
